
package de.msiggi.sportsdata.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Sportsdata", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", wsdlLocation = "http://www.openligadb.de/Webservices/Sportsdata.asmx?WSDL")
public class Sportsdata
    extends Service
{

    private final static URL SPORTSDATA_WSDL_LOCATION;
    private final static WebServiceException SPORTSDATA_EXCEPTION;
    private final static QName SPORTSDATA_QNAME = new QName("http://msiggi.de/Sportsdata/Webservices", "Sportsdata");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.openligadb.de/Webservices/Sportsdata.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SPORTSDATA_WSDL_LOCATION = url;
        SPORTSDATA_EXCEPTION = e;
    }

    public Sportsdata() {
        super(__getWsdlLocation(), SPORTSDATA_QNAME);
    }

    public Sportsdata(WebServiceFeature... features) {
        super(__getWsdlLocation(), SPORTSDATA_QNAME, features);
    }

    public Sportsdata(URL wsdlLocation) {
        super(wsdlLocation, SPORTSDATA_QNAME);
    }

    public Sportsdata(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SPORTSDATA_QNAME, features);
    }

    public Sportsdata(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Sportsdata(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SportsdataSoap
     */
    @WebEndpoint(name = "SportsdataSoap")
    public SportsdataSoap getSportsdataSoap() {
        return super.getPort(new QName("http://msiggi.de/Sportsdata/Webservices", "SportsdataSoap"), SportsdataSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SportsdataSoap
     */
    @WebEndpoint(name = "SportsdataSoap")
    public SportsdataSoap getSportsdataSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://msiggi.de/Sportsdata/Webservices", "SportsdataSoap"), SportsdataSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SPORTSDATA_EXCEPTION!= null) {
            throw SPORTSDATA_EXCEPTION;
        }
        return SPORTSDATA_WSDL_LOCATION;
    }

}
