package de.presentation.popups;

public enum PopupType {
	// General popups
	DEFAULT, HINT, ERROR, PROPERTIES_POPUP,
	// Tipico table popups
	TIPICO_NEW_POPUP, TIPICO_BETVALUE_POPUP, TIPICO_TABLE_FILTER_POPUP,
	// Database popups
	DATABASE_CONNECTION_POPUP, DATABASE_BROWSER_POPUP, DATABASE_PULLDETAIL_POPUP;
}
